In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv(
    "pandas_practice_dataset.csv",
    sep=",",
    header=0,
    index_col=0,
    # usecols=["Name","Age"],
    # nrows=100
)

In [13]:
data = df.head(10)

In [15]:
data.shape
data.index

Index([10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009, 10010], dtype='int64', name='EmployeeID')

In [19]:
data.info

<bound method DataFrame.info of                   Name   Age Gender  Department       City    Salary  \
EmployeeID
10001       Employee_0  59.0      F          IT    Chennai   28484.0
10002       Employee_1  49.0      M       Sales     Mumbai   78987.0
10003       Employee_2  35.0      M  Operations  Hyderabad   43225.0
10004       Employee_3  28.0      F       Sales      Delhi  105459.0
10005       Employee_4  41.0      M   Marketing       Pune  146566.0
10006       Employee_5  59.0      F       Sales  Hyderabad   86104.0
10007       Employee_6  39.0      F          HR       Pune   45936.0
10008       Employee_7  43.0      M       Sales       Pune   64612.0
10009       Employee_8  31.0      F     Finance       Pune  109946.0
10010       Employee_9  31.0      M          HR  Bangalore  120533.0

            Experience  PerformanceScore    JoinDate  Sales  Bonus
EmployeeID
10001               10              4.59  2025-02-03  25885  13348
10002                9              2.53  2025-01-07  83945  20928
10003                0              3.76  2024-08-28  70948  14558
10004               16              3.39  2026-01-14  47075   4818
10005               12              1.21  2024-09-13  86563   9087
10006               13              1.31  2026-05-25  75095  24466
10007                0              1.08  2025-10-18   5650  16204
10008                1              2.48  2023-07-15  77380   4443
10009                1              3.98  2025-09-21  18633  16648
10010                6              1.69  2025-08-03  38343  23093  >

In [23]:
data.describe()

,Age,Salary,Experience,PerformanceScore,Sales,Bonus
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,41.50000,82985.200000,6.800000,2.602000,52951.700000,14759.300000
std,11.16791,37964.159059,6.014797,1.273148,29621.723414,7046.201136
min,28.00000,28484.000000,0.000000,1.080000,5650.000000,4443.000000
25%,32.00000,50605.000000,1.000000,1.405000,28999.500000,10152.250000
50%,40.00000,82545.500000,7.500000,2.505000,59011.500000,15381.000000
75%,47.50000,108824.250000,11.500000,3.667500,76808.750000,19858.000000
max,59.00000,146566.000000,16.000000,4.590000,86563.000000,24466.000000

In [31]:
data[['Name', 'Age']]

                  Name   Age
EmployeeID
10001       Employee_0  59.0
10002       Employee_1  49.0
10003       Employee_2  35.0
10004       Employee_3  28.0
10005       Employee_4  41.0
10006       Employee_5  59.0
10007       Employee_6  39.0
10008       Employee_7  43.0
10009       Employee_8  31.0
10010       Employee_9  31.0

In [40]:
# data.loc[1]
# data.loc[[3,5]]
# data.loc[0, "Name"]
data.head(2)

,Name,Age,Gender,Department,City,Salary,Experience,PerformanceScore,JoinDate,Sales,Bonus
EmployeeID,,,,,,,,,,,
10001,Employee_0,59.0,F,IT,Chennai,28484.0,10,4.59,2025-02-03,25885,13348
10002,Employee_1,49.0,M,Sales,Mumbai,78987.0,9,2.53,2025-01-07,83945,20928

In [52]:
data.iloc[[0,5]]
# data.iloc[["Name", "Gender"]]

,Name,Age,Gender,Department,City,Salary,Experience,PerformanceScore,JoinDate,Sales,Bonus
EmployeeID,,,,,,,,,,,
10001,Employee_0,59.0,F,IT,Chennai,28484.0,10,4.59,2025-02-03,25885,13348
10006,Employee_5,59.0,F,Sales,Hyderabad,86104.0,13,1.31,2026-05-25,75095,24466

In [56]:
data[(data["Age"]>25) & (data["Gender"]=="M")]

,Name,Age,Gender,Department,City,Salary,Experience,PerformanceScore,JoinDate,Sales,Bonus
EmployeeID,,,,,,,,,,,
10002,Employee_1,49.0,M,Sales,Mumbai,78987.0,9,2.53,2025-01-07,83945,20928
10003,Employee_2,35.0,M,Operations,Hyderabad,43225.0,0,3.76,2024-08-28,70948,14558
10005,Employee_4,41.0,M,Marketing,Pune,146566.0,12,1.21,2024-09-13,86563,9087
10008,Employee_7,43.0,M,Sales,Pune,64612.0,1,2.48,2023-07-15,77380,4443
10010,Employee_9,31.0,M,HR,Bangalore,120533.0,6,1.69,2025-08-03,38343,23093

In [57]:
data[data["City"].isin(["Mumbai", "Pune"])]

,Name,Age,Gender,Department,City,Salary,Experience,PerformanceScore,JoinDate,Sales,Bonus
EmployeeID,,,,,,,,,,,
10002,Employee_1,49.0,M,Sales,Mumbai,78987.0,9,2.53,2025-01-07,83945,20928
10005,Employee_4,41.0,M,Marketing,Pune,146566.0,12,1.21,2024-09-13,86563,9087
10007,Employee_6,39.0,F,HR,Pune,45936.0,0,1.08,2025-10-18,5650,16204
10008,Employee_7,43.0,M,Sales,Pune,64612.0,1,2.48,2023-07-15,77380,4443
10009,Employee_8,31.0,F,Finance,Pune,109946.0,1,3.98,2025-09-21,18633,16648